// import { AiFillStar } from "react-icons/ai";
import img1 from "./img-1.jpg";
import img2 from "./img-2.jpg";
import img3 from "./img-3.jpg";
import img4 from "./img-4.jpg";
import img5 from "./img-5.png";
import img6 from "./img-6.png";
import img7 from "./img-7.png";
import img8 from "./img-8.png";
import img9 from "./img-9.png";
import img10 from "./img-10.png";
import img11 from "./img-11.png";
import img12 from "./img-12.png";

const data = [
  {
    img: img4,
    title: "black suits",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    old_price: "$140,00",
    new_price: "200",
    company: "Nike",
    color: "white",
    id: 4,
    category: "wears",
  },
  {
    img: img1,
    title: "men shirt",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    old_price: "$140,00",
    new_price: "200",
    company: "Nike",
    color: "white",
    id: 1,
    category: "wears",
  },
  {
    img: img2,
    title: "parking shirt",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    old_price: "$140,00",
    new_price: "200",
    company: "Nike",
    color: "white",
    id: 2,
    category: "wears",
  },
  {
    img: img3,
    title: "white round neck ",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    old_price: "$140,00",
    new_price: "200",
    company: "Nike",
    color: "white",
    id: 3,
    category: "wears",
  },

  {
    img: img5,
    title: "ribbon tie",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    old_price: "$140,00",
    new_price: "200",
    company: "Nike",
    color: "white",
    id: 5,
    category: "wears",
  },
  {
    img: img6,
    title: "cobbler shoe",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    old_price: "$140,00",
    new_price: "200",
    company: "Nike",
    color: "white",
    id: 6,
    category: "sneakers",
  },
  {
    img: img7,
    title: "cobbler shoe",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    old_price: "$140,00",
    new_price: "200",
    company: "Nike",
    color: "white",
    id: 7,
    category: "sneakers",
  },
  {
    img: img8,
    title: "blue top shirt",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    old_price: "$140,00",
    new_price: "200",
    company: "Nike",
    color: "white",
    id: 8,
    category: "wears",
  },
  {
    img: img9,
    title: "denim jean shirt",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    old_price: "$140,00",
    new_price: "200",
    company: "Nike",
    color: "white",
    id: 9,
    category: "wears",
  },
  {
    img: img10,
    title: "denim jean trouser",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    old_price: "$140,00",
    new_price: "200",
    company: "Nike",
    color: "white",
    id: 10,
    category: "wears",
  },
  {
    img: img11,
    title: "black LV cap",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    old_price: "$140,00",
    new_price: "200",
    company: "Nike",
    color: "white",
    id: 11,
    category: "wears",
  },
  {
    img: img12,
    title: "slouver shoe",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    old_price: "$140,00",
    new_price: "200",
    company: "Nike",
    color: "white",
    id: 12,
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
    title: "Nike Air Vapormax Plus",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(93 reviews)",
    old_price: "$140,00",
    new_price: "200",
    company: "Nike",
    color: "red",
    id: 13,
    category: "sneakers",
  },

  {
    img: "https://m.media-amazon.com/images/I/51+P9uAvb1L._AC_UY695_.jpg",
    title: "Nike Waffle One Sneaker",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    old_price: "$140,00",
    new_price: "200",
    company: "Nike",
    color: "green",
    id: 14,
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/71oEKkghg-L._AC_UX575_.jpg",
    title: "Nike Running Shoe",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    old_price: "$140,00",
    new_price: "200",
    company: "Adidas",
    color: "black",
    id: 15,
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/41M54ztS6IL._AC_SY625._SX._UX._SY._UY_.jpg",
    title: "Flat Slip On Pumps",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    old_price: "$140,00",
    new_price: "200",
    company: "Vans",
    color: "green",
    id: 16,
    category: "flats",
  },
  {
    img: "https://m.media-amazon.com/images/I/71zKuNICJAL._AC_UX625_.jpg",
    title: "Knit Ballet Flat",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    old_price: "$140,00",
    new_price: "50",
    company: "Adidas",
    color: "black",
    id: 17,
    category: "flats",
  },

  {
    img: "https://m.media-amazon.com/images/I/61V9APfz97L._AC_UY695_.jpg",
    title: "Loafer Flats",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    old_price: "$140,00",
    new_price: "50",
    company: "Vans",
    color: "white",
    id: 18,
    category: "flats",
  },

  {
    img: "https://m.media-amazon.com/images/I/71VaQ+V6XnL._AC_UY695_.jpg",
    title: "Nike Zoom Freak",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    old_price: "$140,00",
    new_price: "200",
    company: "Nike",
    color: "green",
    id: 19,
    category: "sneakers",
  },

  {
    img: "https://m.media-amazon.com/images/I/61-cBsLhJHL._AC_UY695_.jpg",
    title: "Nike Men's Sneaker",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    old_price: "$140,00",
    new_price: "200",
    company: "Adidas",
    color: "blue",
    id: 20,
    category: "sneakers",
  },

  {
    img: "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
    title: "PUMA BLACK-OCE",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    old_price: "$140,00",
    new_price: "150",
    company: "Puma",
    color: "green",
    id: 21,
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/71E75yRwCDL._AC_UY575_.jpg",
    title: "Pacer Future Sneaker",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    old_price: "$140,00",
    new_price: "150",
    company: "Puma",
    color: "red",
    id: 22,
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/71jeoX0rMBL._AC_UX575_.jpg",
    title: "Unisex-Adult Super",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    old_price: "$140,00",
    new_price: "150",
    company: "Puma",
    color: "black",
    id: 23,
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/61TM6Q9dvxL._AC_UX575_.jpg",
    title: "Roma Basic Sneaker",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    old_price: "$140,00",
    new_price: "150",
    company: "Puma",
    color: "white",
    id: 24,
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/7128-af7joL._AC_UY575_.jpg",
    title: "Pacer Future Doubleknit",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    old_price: "$140,00",
    new_price: "150",
    company: "Puma",
    color: "black",
    id: 25,
    category: "sneakers",
  },

  {
    img: "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
    title: "Fusion Evo Golf Shoe",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    old_price: "$140,00",
    new_price: "100",
    company: "Puma",
    color: "green",
    id: 26,
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/719gdz8lsTS._AC_UX575_.jpg",
    title: "Rainbow Chex Skate",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    old_price: "$140,00",
    new_price: "100",
    company: "Vans",
    color: "red",
    id: 27,
    category: "flats",
  },
  {
    img: "https://m.media-amazon.com/images/I/71gpFHJlnoL._AC_UX575_.jpg",
    title: "Low-Top Trainers",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    old_price: "$140,00",
    new_price: "100",
    company: "Vans",
    color: "white",
    id: 28,
    category: "sandals",
  },
  {
    img: "https://m.media-amazon.com/images/I/71pf7VFs9CL._AC_UX575_.jpg",
    title: "Vans Unisex Low-Top",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    old_price: "$140,00",
    new_price: "100",
    company: "Vans",
    color: "blue",
    id: 29,
    category: "sandals",
  },
  {
    img: "https://m.media-amazon.com/images/I/61N4GyWcHPL._AC_UY575_.jpg",
    title: "Classic Bandana Sneakers",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    old_price: "$140,00",
    new_price: "50",
    company: "Nike",
    color: "black",
    id: 30,
    category: "sandals",
  },
  {
    img: "https://m.media-amazon.com/images/I/61bncQ44yML._AC_UX695_.jpg",
    title: "Chunky High Heel",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    old_price: "$140,00",
    new_price: "50",
    company: "Vans",
    color: "black",
    id: 31,
    category: "heels",
  },
  {
    img: "https://m.media-amazon.com/images/I/71czu7WgGuL._AC_UY695_.jpg",
    title: "Slip On Stiletto High Heel",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    old_price: "$140,00",
    new_price: "100",
    company: "puma",
    color: "black",
    id: 32,
    category: "heels",
  },
  {
    img: "https://m.media-amazon.com/images/I/61men05KRxL._AC_UY625_.jpg",
    title: "DREAM PAIRS Court Shoes",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    old_price: "$140,00",
    new_price: "150",
    company: "Nike",
    color: "red",
    id: 33,
    category: "heels",
  },
  {
    img: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
    title: "Nike Air Vapormax Plus",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    old_price: "$140,00",
    new_price: "200",
    company: "Nike",
    color: "red",
    id: 34,
    category: "sneakers",
  },

  {
    img: "https://m.media-amazon.com/images/I/51PGWTXgf-L._AC_UY625_.jpg",
    title: "Low Mid Block Heels",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    old_price: "$140,00",
    new_price: "200",
    company: "Nike",
    color: "black",
    id: 35,
    category: "heels",
  },
  {
    img: "https://m.media-amazon.com/images/I/616sA5XUKtL._AC_UY675_.jpg",
    title: "Chunky High Heel",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    old_price: "$140,00",
    new_price: "50",
    company: "Adidas",
    color: "black",
    id: 36,
    category: "heels",
  },
  {
    img: "https://m.media-amazon.com/images/I/71h5+MbEK7L._AC_UY625_.jpg",
    title: "Amore Fashion Stilettos",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    old_price: "$140,00",
    new_price: "150",
    company: "Adidas",
    color: "white",
    id: 37,
    category: "heels",
  },
  {
    img: "https://m.media-amazon.com/images/I/61uw5RDxKQL._AC_UY625_.jpg",
    title: "Bridal Sandals Glitter",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    old_price: "$140,00",
    new_price: "50",
    company: "Adidas",
    color: "black",
    id: 38,
    category: "heels",
  },
  {
    img: "https://m.media-amazon.com/images/I/71yhoZP0l6L._AC_UY695_.jpg",
    title: "Wedding Prom Bridal",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    old_price: "$140,00",
    new_price: "50",
    company: "Adidas",
    color: "black",
    id: 39,
    category: "flats",
  },
];

export default data;
