import img1 from "./img-1.jpg";
import img2 from "./img-2.jpg";
import img3 from "./img-3.jpg";
import img4 from "./img-4.jpg";

let data_product = [
  {
    img: img1,
    title: "men shirt",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    old_price: "$140,00",
    new_price: "200",
    company: "Nike",
    color: "white",
    id: 1,
    category: "wears",
  },
  {
    img: img2,
    title: "parking shirt",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    old_price: "$140,00",
    new_price: "200",
    company: "Nike",
    color: "white",
    id: 2,
    category: "wears",
  },
  {
    img: img3,
    title: "white round neck ",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    old_price: "$140,00",
    new_price: "200",
    company: "Nike",
    color: "white",
    id: 3,
    category: "wears",
  },
  {
    img: img4,
    title: "black suits",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    old_price: "$140,00",
    new_price: "200",
    company: "Nike",
    color: "white",
    id: 4,
    category: "wears",
  },
  //   {
  //     img: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
  //     title: "Nike Air Vapormax Plus",
  //     // star: <AiFillStar className="rating-star" />,
  //     reviews: "(93 reviews)",
  //     old_price: "$140,00",
  //     new_price: "200",
  //     company: "Nike",
  //     color: "red",
  //     id: 1,
  //     category: "sneakers",
  //   },

  //   {
  //     img: "https://m.media-amazon.com/images/I/51+P9uAvb1L._AC_UY695_.jpg",
  //     title: "Nike Waffle One Sneaker",
  //     // star: <AiFillStar className="rating-star" />,
  //     reviews: "(123 reviews)",
  //     old_price: "$140,00",
  //     new_price: "200",
  //     company: "Nike",
  //     color: "green",
  //     id: 2,
  //     category: "sneakers",
  //   },
  //   {
  //     img: "https://m.media-amazon.com/images/I/71oEKkghg-L._AC_UX575_.jpg",
  //     title: "Nike Running Shoe",
  //     // star: <AiFillStar className="rating-star" />,
  //     reviews: "(123 reviews)",
  //     old_price: "$140,00",
  //     new_price: "200",
  //     company: "Adidas",
  //     color: "black",
  //     id: 3,
  //     category: "sneakers",
  //   },
  //   {
  //     img: "https://m.media-amazon.com/images/I/41M54ztS6IL._AC_SY625._SX._UX._SY._UY_.jpg",
  //     title: "Flat Slip On Pumps",
  //     // star: <AiFillStar className="rating-star" />,
  //     reviews: "(123 reviews)",
  //     old_price: "$140,00",
  //     new_price: "200",
  //     company: "Vans",
  //     color: "green",
  //     id: 4,
  //     category: "flats",
  //   },
];

export default data_product;
